// Memory bus encodings: SIZE, TRANS, PROT, LOCK, WRITE direction, plus a
// burst-increment helper. Bus protocol per TRM Ch. 3 and TASKS.md §17/§30.17.

package arm7tdmis_bus_pkg;

    // ---- SIZE[1:0] (TRM §3.4.3 Table 3-3 / §30.17.3).
    // 2'b11 is reserved and must never be generated by the core.
    typedef enum logic [1:0] {
        SIZE_BYTE     = 2'b00,
        SIZE_HALFWORD = 2'b01,
        SIZE_WORD     = 2'b10,
        SIZE_RESERVED = 2'b11
    } size_e;

    // ---- TRANS[1:0] (TRM Table 3-1).
    // I-cycle: idle, no memory access this cycle.
    // C-cycle: coprocessor register transfer (no main memory access).
    // N-cycle: nonsequential memory access — start of burst.
    // S-cycle: sequential memory access — burst continuation.
    typedef enum logic [1:0] {
        TRANS_I = 2'b00,
        TRANS_C = 2'b01,
        TRANS_N = 2'b10,
        TRANS_S = 2'b11
    } trans_e;

    // ---- PROT[1:0] (TRM §3.4 / Appendix A).
    // PROT[0] = 0 opcode fetch, 1 data access.
    // PROT[1] = 0 user mode,   1 privileged mode.
    // Code paths typically set the two bits independently from decode/CPSR;
    // the named enum below is for whole-value comparisons in tb/assertions.
    localparam int unsigned PROT_BIT_DATA = 0;
    localparam int unsigned PROT_BIT_PRIV = 1;

    typedef enum logic [1:0] {
        PROT_OPC_USR  = 2'b00,
        PROT_OPC_PRIV = 2'b10,
        PROT_DAT_USR  = 2'b01,
        PROT_DAT_PRIV = 2'b11
    } prot_e;

    // ---- WRITE direction ----
    localparam logic WRITE_READ  = 1'b0;
    localparam logic WRITE_WRITE = 1'b1;

    // ---- LOCK (TRM §30.13: HIGH for both data cycles of SWP/SWPB) ----
    localparam logic LOCK_FREE   = 1'b0;
    localparam logic LOCK_LOCKED = 1'b1;

    // ---- Burst increment per S cycle (§30.17.2): word=+4, halfword=+2.
    // Byte bursts and SIZE_RESERVED are illegal; return 0 so a stuck-burst
    // assertion can fire downstream.
    function automatic logic [31:0] burst_increment(input size_e sz);
        unique case (sz)
            SIZE_WORD:     return 32'd4;
            SIZE_HALFWORD: return 32'd2;
            default:       return 32'd0;
        endcase
    endfunction

endpackage
