#!/usr/bin/env python3
"""Build fail-hard ARMv4T encoding-family functional-coverage evidence."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import pathlib
import re
import subprocess
import sys
from typing import Any


SCHEMA = "arm7tdmis-functional-coverage-v1"
MANIFEST_SCHEMA = "arm7tdmis-functional-coverage-map-v1"
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "verification/functional_coverage.json"
DEFAULT_REGRESSION = REPO_ROOT / "reports/generated/regression.json"
DEFAULT_OUTPUT = (
    REPO_ROOT / "reports/generated/functional-coverage-report.json"
)

ARM_CLASSES = (
    "undef",
    "dp",
    "msr",
    "mrs",
    "mul",
    "mull",
    "branch",
    "bx",
    "ldr_str",
    "ldrh_strh",
    "ldm_stm",
    "swp",
    "swi",
    "cdp",
    "mcr_mrc",
    "ldc_stc",
)
ARM_CLASS_TOTALS = {
    "undef": 445,
    "dp": 784,
    "msr": 34,
    "mrs": 2,
    "mul": 4,
    "mull": 8,
    "branch": 512,
    "bx": 1,
    "ldr_str": 768,
    "ldrh_strh": 64,
    "ldm_stm": 512,
    "swp": 2,
    "swi": 256,
    "cdp": 128,
    "mcr_mrc": 128,
    "ldc_stc": 448,
}
DP_NAMES = (
    "and",
    "eor",
    "sub",
    "rsb",
    "add",
    "adc",
    "sbc",
    "rsc",
    "tst",
    "teq",
    "cmp",
    "cmn",
    "orr",
    "mov",
    "bic",
    "mvn",
)
CONDITION_NAMES = (
    "eq",
    "ne",
    "cs",
    "cc",
    "mi",
    "pl",
    "vs",
    "vc",
    "hi",
    "ls",
    "ge",
    "lt",
    "gt",
    "le",
    "al",
)
THUMB_ALU_NAMES = (
    "and",
    "eor",
    "lsl",
    "lsr",
    "asr",
    "adc",
    "sbc",
    "ror",
    "tst",
    "neg",
    "cmp",
    "cmn",
    "orr",
    "mul",
    "bic",
    "mvn",
)
EXPECTED_GROUP_IDS = {
    "arm.class",
    "arm.condition",
    "arm.dp_opcode",
    "arm.shifter",
    "arm.multiply",
    "arm.psr",
    "arm.branch",
    "arm.single_transfer",
    "arm.extra_transfer",
    "arm.block_transfer",
    "arm.block_operands",
    "arm.swap",
    "arm.coprocessor",
    "thumb.format",
    "thumb.alu",
    "thumb.condition",
    "thumb.subfamily",
    "exception.reserved",
    "exception.policy",
}
EXPECTED_DOMAINS = {
    "arm_decode_rows": 4096,
    "arm_nv_rows": 4096,
    "thumb_words": 65536,
    "arm_static_policy_rows": 1066,
    "thumb_static_policy_rows": 448,
}
ARM_STATIC_POLICY_COMPONENTS = {
    # These are the independently counted rows generated by
    # unpredictable_decode_tb: allocated DP fields, short/long multiply
    # operands, PSR operands, MRS/MSR/BX/SWP/extra-transfer SBZ/SBO fields,
    # and coprocessor load/store writeback to r15.
    "data_processing_fields": 2 * ((4 * 15) + (2 * 15)),
    "short_multiply_operands": 14 + 7,
    "long_multiply_operands": 4 * (4 + 15),
    "psr_operands": 8,
    "psr_misc_fields": 2 * ((3 * 15) + 255 + 15),
    "bx_sbo_fields": 3 * 15,
    "swp_sbz_fields": 2 * 15,
    "extra_transfer_sbz_fields": 4 * 15,
    "coprocessor_pc_writeback": 2 * 2 * 2 * 2,
}


def _utc_now() -> str:
    return dt.datetime.now(dt.UTC).isoformat(timespec="seconds")


def _sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _file_entry(path: pathlib.Path) -> dict[str, Any]:
    resolved = path.resolve()
    return {
        "path": resolved.relative_to(REPO_ROOT).as_posix(),
        "bytes": resolved.stat().st_size,
        "sha256": _sha256(resolved),
    }


def _atomic_json(path: pathlib.Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)


def _git_text(*arguments: str) -> str:
    return subprocess.run(
        ("git", *arguments),
        cwd=REPO_ROOT,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    ).stdout.strip()


def required_bin_ids(manifest: dict[str, Any]) -> list[str]:
    return sorted(
        f"{group['id']}.{member}"
        for group in manifest.get("required_bin_groups", [])
        for member in group.get("members", [])
    )


def validate_manifest(manifest: dict[str, Any]) -> None:
    if manifest.get("schema") != MANIFEST_SCHEMA:
        raise ValueError("functional-coverage manifest has wrong schema")
    if manifest.get("domains") != EXPECTED_DOMAINS:
        raise ValueError("functional-coverage domain sizes were weakened")
    groups = manifest.get("required_bin_groups")
    if (
        not isinstance(groups, list)
        or any(not isinstance(group, dict) for group in groups)
        or {group.get("id") for group in groups} != EXPECTED_GROUP_IDS
    ):
        raise ValueError("functional-coverage required groups are incomplete")
    evidence_phases = {
        entry.get("phase") for entry in manifest.get("evidence", [])
    }
    if None in evidence_phases or len(evidence_phases) != len(
        manifest.get("evidence", [])
    ):
        raise ValueError("functional-coverage evidence phases are malformed")

    for group in groups:
        members = group.get("members")
        if (
            group.get("kind")
            not in {"encoding-family", "exceptional-reserved"}
            or group.get("coverage") not in {"enumerated", "evidence"}
            or not isinstance(members, list)
            or not members
            or len(members) != len(set(members))
            or not isinstance(group.get("citation"), str)
            or not re.search(
                r"(ARM DDI 0100|ARM DDI 0234|ARMv4T)",
                group["citation"],
            )
            or not isinstance(group.get("evidence"), list)
            or not group["evidence"]
            or not set(group["evidence"]) <= evidence_phases
        ):
            raise ValueError(
                f"functional-coverage group is malformed: {group.get('id')}"
            )

    group_members = {
        group["id"]: set(group["members"]) for group in groups
    }
    foundations = {
        "arm.class": set(ARM_CLASSES),
        "arm.condition": set(CONDITION_NAMES),
        "arm.dp_opcode": set(DP_NAMES),
        "arm.multiply": {
            "mul",
            "mla",
            "umull",
            "umlal",
            "smull",
            "smlal",
        },
        "arm.coprocessor": {"cdp", "mcr", "mrc", "ldc", "stc"},
        "thumb.format": {f"{number:02d}" for number in range(1, 20)},
        "thumb.alu": set(THUMB_ALU_NAMES),
        "thumb.condition": set(CONDITION_NAMES[:-1]),
    }
    for group_id, expected in foundations.items():
        if group_members.get(group_id) != expected:
            raise ValueError(
                f"functional-coverage foundation changed: {group_id}"
            )
    bins = required_bin_ids(manifest)
    if len(bins) < 180 or len(bins) != len(set(bins)):
        raise ValueError("functional-coverage required-bin set is too small")

    exclusions = manifest.get("exclusions")
    if not isinstance(exclusions, list) or not exclusions:
        raise ValueError("functional-coverage exclusions are missing")
    for exclusion in exclusions:
        if (
            not isinstance(exclusion, dict)
            or not exclusion.get("id")
            or not exclusion.get("pattern")
            or not exclusion.get("rationale")
            or not re.search(
                r"(ARM DDI 0100|ARM DDI 0234|ARMv4T)",
                str(exclusion.get("citation", "")),
            )
        ):
            raise ValueError("functional-coverage exclusion is uncited")
    for evidence in manifest.get("evidence", []):
        if (
            set(evidence) != {"phase", "source", "marker"}
            or not isinstance(evidence["marker"], str)
            or not evidence["marker"]
        ):
            raise ValueError("functional-coverage evidence entry is malformed")


def _arm_class(op_hi: int, op_lo: int) -> str:
    major = (op_hi >> 5) & 0x7
    if major == 0:
        if op_lo & 0x8 and op_lo & 0x1:
            if op_lo == 0x9:
                if 0x00 <= op_hi <= 0x03:
                    return "mul"
                if 0x08 <= op_hi <= 0x0F:
                    return "mull"
                if op_hi in (0x10, 0x14):
                    return "swp"
                return "undef"
            if op_lo == 0xB:
                return "ldrh_strh"
            if op_lo in (0xD, 0xF):
                return "ldrh_strh" if op_hi & 1 else "undef"
            return "undef"
        if op_hi in (0x10, 0x12, 0x14, 0x16):
            if op_hi in (0x10, 0x14) and op_lo == 0:
                return "mrs"
            if op_hi in (0x12, 0x16) and op_lo == 0:
                return "msr"
            if op_hi == 0x12 and op_lo == 1:
                return "bx"
            return "undef"
        return "dp"
    if major == 1:
        if op_hi in (0x30, 0x34):
            return "undef"
        if op_hi in (0x32, 0x36):
            return "msr"
        return "dp"
    if major == 2:
        return "ldr_str"
    if major == 3:
        return "undef" if op_lo & 1 else "ldr_str"
    if major == 4:
        return "ldm_stm"
    if major == 5:
        return "branch"
    if major == 6:
        if (op_hi >> 3) == 0b11000 and not (op_hi & 0x2):
            return "undef"
        return "ldc_stc"
    if op_hi & 0x10:
        return "swi"
    return "mcr_mrc" if op_lo & 1 else "cdp"


def _arm_bins(op_hi: int, op_lo: int, arm_class: str) -> set[str]:
    bins = {f"arm.class.{arm_class}"}
    if arm_class == "dp":
        bins.add(f"arm.dp_opcode.{DP_NAMES[(op_hi >> 1) & 0xF]}")
        if op_hi & 0x20:
            bins.add("arm.shifter.immediate_rotate")
        else:
            shift = ("lsl", "lsr", "asr", "ror")[(op_lo >> 1) & 0x3]
            if op_lo & 1:
                bins.add(f"arm.shifter.{shift}_register")
            elif shift == "ror" and not (op_lo & 0x8):
                bins.add("arm.shifter.rrx")
            else:
                bins.add(f"arm.shifter.{shift}_immediate")
    elif arm_class in {"mrs", "msr"}:
        psr = "spsr" if op_hi & 0x4 else "cpsr"
        if arm_class == "mrs":
            bins.add(f"arm.psr.mrs_{psr}")
        else:
            form = "immediate" if op_hi & 0x20 else "register"
            bins.add(f"arm.psr.msr_{form}_{psr}")
    elif arm_class == "mul":
        bins.add("arm.multiply.mla" if op_hi & 0x2 else "arm.multiply.mul")
    elif arm_class == "mull":
        signed = bool(op_hi & 0x4)
        accumulate = bool(op_hi & 0x2)
        name = (
            "smlal"
            if signed and accumulate
            else "smull"
            if signed
            else "umlal"
            if accumulate
            else "umull"
        )
        bins.add(f"arm.multiply.{name}")
    elif arm_class == "branch":
        bins.add("arm.branch.bl" if op_hi & 0x10 else "arm.branch.b")
    elif arm_class == "bx":
        bins.add("arm.branch.bx")
    elif arm_class == "ldr_str":
        pre = bool(op_hi & 0x10)
        up = bool(op_hi & 0x8)
        byte = bool(op_hi & 0x4)
        explicit_writeback = bool(op_hi & 0x2)
        load = bool(op_hi & 0x1)
        bins.add(
            "arm.single_transfer."
            + ("ldrb" if load and byte else "ldr" if load else
               "strb" if byte else "str")
        )
        bins.add(
            "arm.single_transfer."
            + ("register_offset" if op_hi & 0x20 else "immediate_offset")
        )
        bins.add("arm.single_transfer.pre_index" if pre
                 else "arm.single_transfer.post_index")
        bins.add("arm.single_transfer.up" if up
                 else "arm.single_transfer.down")
        bins.add(
            "arm.single_transfer.writeback"
            if not pre or explicit_writeback
            else "arm.single_transfer.no_writeback"
        )
        if not pre and explicit_writeback:
            bins.add(
                "arm.single_transfer.translated_load"
                if load
                else "arm.single_transfer.translated_store"
            )
    elif arm_class == "ldrh_strh":
        pre = bool(op_hi & 0x10)
        up = bool(op_hi & 0x8)
        immediate = bool(op_hi & 0x4)
        explicit_writeback = bool(op_hi & 0x2)
        load = bool(op_hi & 0x1)
        sh = (op_lo >> 1) & 0x3
        operation = (
            "strh"
            if sh == 1 and not load
            else "ldrh"
            if sh == 1
            else "ldrsb"
            if sh == 2
            else "ldrsh"
        )
        bins.add(f"arm.extra_transfer.{operation}")
        bins.add(
            "arm.extra_transfer."
            + ("immediate_offset" if immediate else "register_offset")
        )
        bins.add("arm.extra_transfer.pre_index" if pre
                 else "arm.extra_transfer.post_index")
        bins.add("arm.extra_transfer.up" if up
                 else "arm.extra_transfer.down")
        bins.add(
            "arm.extra_transfer.writeback"
            if not pre or explicit_writeback
            else "arm.extra_transfer.no_writeback"
        )
    elif arm_class == "ldm_stm":
        pre = bool(op_hi & 0x10)
        up = bool(op_hi & 0x8)
        s_bit = bool(op_hi & 0x4)
        writeback = bool(op_hi & 0x2)
        load = bool(op_hi & 0x1)
        bins.add("arm.block_transfer.ldm" if load
                 else "arm.block_transfer.stm")
        mode = (
            "ib" if up and pre else
            "ia" if up else
            "db" if pre else
            "da"
        )
        bins.add(f"arm.block_transfer.{mode}")
        bins.add(
            "arm.block_transfer.writeback"
            if writeback
            else "arm.block_transfer.no_writeback"
        )
        if s_bit:
            # Decode rows alone establish allocation of S. Register-list
            # semantics are separately required by arm.block_operands.
            bins.add("arm.block_operands.user_bank")
    elif arm_class == "swp":
        bins.add("arm.swap.swpb" if op_hi & 0x4 else "arm.swap.swp")
    elif arm_class == "cdp":
        bins.add("arm.coprocessor.cdp")
    elif arm_class == "mcr_mrc":
        bins.add("arm.coprocessor.mrc" if op_hi & 1
                 else "arm.coprocessor.mcr")
    elif arm_class == "ldc_stc":
        bins.add("arm.coprocessor.ldc" if op_hi & 1
                 else "arm.coprocessor.stc")
    return bins


def _thumb_reserved(word: int) -> bool:
    return (
        0xB100 <= word <= 0xB3FF
        or 0xB600 <= word <= 0xBBFF
        or 0xBE00 <= word <= 0xBFFF
        or 0xDE00 <= word <= 0xDEFF
        or 0xE800 <= word <= 0xEFFF
    )


def _thumb_policy_unpredictable(word: int) -> bool:
    is_format5 = (word >> 10) == 0b010001
    operation = (word >> 8) & 0x3
    return is_format5 and (
        (
            operation != 3
            and (
                (not (word & 0x80) and not (word & 0x40))
                or (
                    operation == 1
                    and (((word >> 4) & 0x8) | (word & 0x7)) == 15
                )
            )
        )
        or (
            operation == 3
            and (bool(word & 0x80) or (word & 0x7) != 0)
        )
    )


def _thumb_format(word: int) -> int | None:
    if word < 0x1800:
        return 1
    if word < 0x2000:
        return 2
    if word < 0x4000:
        return 3
    if word < 0x4400:
        return 4
    if word < 0x4800:
        return 5
    if word < 0x5000:
        return 6
    if word < 0x6000:
        return 8 if word & 0x0200 else 7
    if word < 0x8000:
        return 9
    if word < 0x9000:
        return 10
    if word < 0xA000:
        return 11
    if word < 0xB000:
        return 12
    if word < 0xB100:
        return 13
    if 0xB400 <= word < 0xB600 or 0xBC00 <= word < 0xBE00:
        return 14
    if 0xC000 <= word < 0xD000:
        return 15
    if 0xD000 <= word < 0xDE00:
        return 16
    if 0xDF00 <= word < 0xE000:
        return 17
    if 0xE000 <= word < 0xE800:
        return 18
    if 0xF000 <= word <= 0xFFFF:
        return 19
    return None


def _thumb_bins(word: int, format_number: int) -> set[str]:
    bins = {f"thumb.format.{format_number:02d}"}
    if format_number == 1:
        bins.add(
            "thumb.subfamily.fmt1_"
            + ("lsl", "lsr", "asr")[(word >> 11) & 0x3]
        )
    elif format_number == 2:
        immediate = bool(word & 0x0400)
        subtract = bool(word & 0x0200)
        bins.add(
            "thumb.subfamily.fmt2_"
            + ("sub" if subtract else "add")
            + ("_immediate" if immediate else "_register")
        )
    elif format_number == 3:
        bins.add(
            "thumb.subfamily.fmt3_"
            + ("mov", "cmp", "add", "sub")[(word >> 11) & 0x3]
        )
    elif format_number == 4:
        bins.add(f"thumb.alu.{THUMB_ALU_NAMES[(word >> 6) & 0xF]}")
    elif format_number == 5:
        bins.add(
            "thumb.subfamily."
            + ("fmt5_add_high", "fmt5_cmp_high", "fmt5_mov_high", "fmt5_bx")[
                (word >> 8) & 0x3
            ]
        )
    elif format_number == 6:
        bins.add("thumb.subfamily.fmt6_ldr_literal")
    elif format_number == 7:
        bins.add(
            "thumb.subfamily."
            + ("fmt7_str", "fmt7_strb", "fmt7_ldr", "fmt7_ldrb")[
                (word >> 10) & 0x3
            ]
        )
    elif format_number == 8:
        bins.add(
            "thumb.subfamily."
            + ("fmt8_strh", "fmt8_ldrsb", "fmt8_ldrh", "fmt8_ldrsh")[
                (word >> 10) & 0x3
            ]
        )
    elif format_number == 9:
        bins.add(
            "thumb.subfamily."
            + ("fmt9_str", "fmt9_ldr", "fmt9_strb", "fmt9_ldrb")[
                (word >> 11) & 0x3
            ]
        )
    elif format_number == 10:
        bins.add(
            "thumb.subfamily.fmt10_"
            + ("ldrh" if word & 0x0800 else "strh")
        )
    elif format_number == 11:
        bins.add(
            "thumb.subfamily.fmt11_"
            + ("ldr_sp" if word & 0x0800 else "str_sp")
        )
    elif format_number == 12:
        bins.add(
            "thumb.subfamily.fmt12_"
            + ("add_sp" if word & 0x0800 else "add_pc")
        )
    elif format_number == 13:
        bins.add(
            "thumb.subfamily.fmt13_"
            + ("sub_sp" if word & 0x0080 else "add_sp")
        )
    elif format_number == 14:
        load = bool(word & 0x0800)
        extension = bool(word & 0x0100)
        bins.add(
            "thumb.subfamily.fmt14_pop"
            if load
            else "thumb.subfamily.fmt14_push"
        )
        if extension:
            bins.add(
                "thumb.subfamily.fmt14_pop_pc"
                if load
                else "thumb.subfamily.fmt14_push_lr"
            )
    elif format_number == 15:
        bins.add(
            "thumb.subfamily.fmt15_ldmia"
            if word & 0x0800
            else "thumb.subfamily.fmt15_stmia"
        )
    elif format_number == 16:
        bins.add(f"thumb.condition.{CONDITION_NAMES[(word >> 8) & 0xF]}")
    elif format_number == 17:
        bins.add("thumb.subfamily.fmt17_swi")
    elif format_number == 18:
        bins.add("thumb.subfamily.fmt18_b")
    elif format_number == 19:
        bins.add(
            "thumb.subfamily.fmt19_bl_suffix"
            if word & 0x0800
            else "thumb.subfamily.fmt19_bl_prefix"
        )
    return bins


def enumerate_reference_coverage(
    manifest: dict[str, Any],
) -> dict[str, Any]:
    """Enumerate the complete independent ARM/Thumb allocation domains."""
    validate_manifest(manifest)
    covered: set[str] = set()
    class_counts = {name: 0 for name in ARM_CLASSES}
    arm_decode_rows = 0
    for op_hi in range(256):
        for op_lo in range(16):
            arm_decode_rows += 1
            arm_class = _arm_class(op_hi, op_lo)
            class_counts[arm_class] += 1
            covered.update(_arm_bins(op_hi, op_lo, arm_class))
    if class_counts != ARM_CLASS_TOTALS:
        raise ValueError("independent ARM allocation totals changed")
    if arm_decode_rows != EXPECTED_DOMAINS["arm_decode_rows"]:
        raise ValueError("independent ARM decode domain is incomplete")

    # ARMv4T reserves condition 1111. Enumerate the same complete lower
    # decode-bit domain with NV supplied, independently of the RTL run.
    arm_nv_rows = 0
    for condition in (0xF,):
        for _op_hi in range(256):
            for _op_lo in range(16):
                if condition != 0xF:
                    raise ValueError("ARM NV reference condition changed")
                arm_nv_rows += 1
    if arm_nv_rows != EXPECTED_DOMAINS["arm_nv_rows"]:
        raise ValueError("independent ARM NV domain is incomplete")

    # Conditions are externally supplied fields rather than part of the
    # 12-bit allocation map. The exhaustive condition/mode execution phase is
    # still required before these evidence-covered bins close.
    for condition in CONDITION_NAMES:
        covered.add(f"arm.condition.{condition}")

    thumb_words = 0
    thumb_policy_rows = 0
    for word in range(65536):
        thumb_words += 1
        if _thumb_policy_unpredictable(word):
            thumb_policy_rows += 1
        if _thumb_reserved(word) or _thumb_policy_unpredictable(word):
            continue
        format_number = _thumb_format(word)
        if format_number is None:
            raise ValueError(f"valid Thumb word lacks a format: {word:04x}")
        covered.update(_thumb_bins(word, format_number))
    if thumb_policy_rows != 448:
        raise ValueError("independent Thumb policy total changed")
    if thumb_words != EXPECTED_DOMAINS["thumb_words"]:
        raise ValueError("independent Thumb domain is incomplete")

    arm_policy_rows = sum(ARM_STATIC_POLICY_COMPONENTS.values())
    observations = {
        "arm_decode_rows": arm_decode_rows,
        "arm_nv_rows": arm_nv_rows,
        "thumb_words": thumb_words,
        "arm_static_policy_rows": arm_policy_rows,
        "thumb_static_policy_rows": thumb_policy_rows,
    }
    if observations != EXPECTED_DOMAINS:
        raise ValueError("independent functional-coverage domains changed")

    # Operand-list semantics sit outside the ARM 12-bit allocation domain.
    # Their evidence group closes only after the execution matrices pass.
    domains = {
        name: {"expected": expected, "observed": observations[name]}
        for name, expected in EXPECTED_DOMAINS.items()
    }
    return {
        "domains": domains,
        "covered_bins": sorted(covered),
        "arm_class_counts": class_counts,
        "arm_static_policy_components": ARM_STATIC_POLICY_COMPONENTS,
    }


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--manifest", type=pathlib.Path, default=DEFAULT_MANIFEST
    )
    parser.add_argument(
        "--regression", type=pathlib.Path, default=DEFAULT_REGRESSION
    )
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    manifest_path = (
        args.manifest
        if args.manifest.is_absolute()
        else REPO_ROOT / args.manifest
    ).resolve()
    regression_path = (
        args.regression
        if args.regression.is_absolute()
        else REPO_ROOT / args.regression
    ).resolve()
    output_path = (
        args.output if args.output.is_absolute() else REPO_ROOT / args.output
    ).resolve()
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    regression = json.loads(regression_path.read_text(encoding="utf-8"))
    validate_manifest(manifest)

    commit = _git_text("rev-parse", "HEAD")
    dirty = bool(_git_text("status", "--porcelain"))
    if dirty:
        raise ValueError("functional coverage requires a clean source tree")
    if (
        regression.get("schema") != "arm7tdmis-regression-v1"
        or regression.get("mode") != "full"
        or regression.get("git", {}).get("commit") != commit
        or regression.get("git", {}).get("dirty")
        or regression.get("status") not in {"running", "passed"}
    ):
        raise ValueError(
            "functional coverage requires the current clean full regression"
        )

    results = regression.get("results")
    if not isinstance(results, list):
        raise ValueError("regression result list is malformed")
    result_by_name = {
        str(result.get("name")): result for result in results
    }
    evidence_report: dict[str, Any] = {}
    for evidence in manifest["evidence"]:
        phase = evidence["phase"]
        result = result_by_name.get(phase)
        if (
            result is None
            or result.get("status") != "passed"
            or result.get("exit_code") != 0
        ):
            raise ValueError(
                f"required functional-coverage phase did not pass: {phase}"
            )
        log_path = (REPO_ROOT / str(result.get("log", ""))).resolve()
        source_path = (REPO_ROOT / evidence["source"]).resolve()
        if (
            not log_path.is_file()
            or _sha256(log_path) != result.get("log_sha256")
            or not source_path.is_file()
        ):
            raise ValueError(
                f"functional-coverage evidence hash is invalid: {phase}"
            )
        log_text = log_path.read_text(encoding="utf-8", errors="replace")
        if re.search(evidence["marker"], log_text) is None:
            raise ValueError(
                f"functional-coverage PASS marker is missing: {phase}"
            )
        evidence_report[phase] = {
            "status": "passed",
            "marker": evidence["marker"],
            "log": _file_entry(log_path),
            "source": _file_entry(source_path),
        }

    reference = enumerate_reference_coverage(manifest)
    covered = set(reference["covered_bins"])
    for group in manifest["required_bin_groups"]:
        if group["coverage"] == "evidence":
            if not set(group["evidence"]) <= set(evidence_report):
                raise ValueError(
                    f"functional-coverage group lacks evidence: {group['id']}"
                )
            covered.update(
                f"{group['id']}.{member}" for member in group["members"]
            )
    required = required_bin_ids(manifest)
    covered_required = sorted(set(required) & covered)
    uncovered = sorted(set(required) - covered)
    report = {
        "schema": SCHEMA,
        "created_utc": _utc_now(),
        "status": "passed" if not uncovered else "failed",
        "git": {"commit": commit, "dirty": dirty},
        "regression": {
            "schema": regression["schema"],
            "path": regression_path.relative_to(REPO_ROOT).as_posix(),
            "commit": regression["git"]["commit"],
            "mode": regression["mode"],
            "status_when_sampled": regression["status"],
        },
        "domains": reference["domains"],
        "arm_class_counts": reference["arm_class_counts"],
        "arm_static_policy_components": reference[
            "arm_static_policy_components"
        ],
        "required_bin_count": len(required),
        "required_bins": required,
        "covered_bin_count": len(covered_required),
        "covered_bins": covered_required,
        "uncovered_bins": uncovered,
        "exclusions": manifest["exclusions"],
        "evidence": evidence_report,
        "inputs": {
            manifest_path.relative_to(REPO_ROOT).as_posix(): _file_entry(
                manifest_path
            ),
            pathlib.Path(__file__).resolve().relative_to(
                REPO_ROOT
            ).as_posix(): _file_entry(pathlib.Path(__file__).resolve()),
        },
    }
    _atomic_json(output_path, report)
    if uncovered:
        print(
            "[functional-coverage] FAIL uncovered="
            + ",".join(uncovered),
            file=sys.stderr,
        )
        return 1
    print(
        "[functional-coverage] PASS "
        f"({len(required)} required bins, zero uncovered; "
        "4096 ARM + 4096 NV + 65536 Thumb rows)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
