# Common 25 MHz boundary used only for like-for-like option-cost fits.
create_clock -name CLK -period 40.000 [get_ports {CLK}]
derive_clock_uncertainty

set_false_path -from [get_ports {
    RESET_N
    IRQ_ASYNC
    FIQ_ASYNC
    DEBUG_ENABLE_ASYNC
    DBGRQ_ASYNC
    DBGBREAK_ASYNC
    DBGEXT_ASYNC[*]
}]

set_input_delay -clock CLK -min 0.250 [get_ports {
    CPU_CE MEM_READY MEM_RDATA[*] MEM_ERROR
    CPA CPB
    DBG_STEP_VALID DBG_STEP_TMS DBG_STEP_TDI DBG_STEP_RSP_READY
}]
set_input_delay -clock CLK -max 5.000 [get_ports {
    CPU_CE MEM_READY MEM_RDATA[*] MEM_ERROR
    CPA CPB
    DBG_STEP_VALID DBG_STEP_TMS DBG_STEP_TDI DBG_STEP_RSP_READY
}]

set_output_delay -clock CLK -min 0.000 [get_ports {
    MEM_VALID MEM_ADDR[*] MEM_WRITE MEM_WDATA[*] MEM_BYTE_ENABLE[*]
    MEM_CODE MEM_PRIVILEGED MEM_LOCK MEM_SEQUENTIAL MEM_MORE
    CPnMREQ CPSEQ CPnTRANS CPnOPC CPTBIT CPnI
    DBG_STEP_READY DBG_STEP_RSP_VALID DBG_STEP_TDO DBG_STEP_TDO_OE
    DBGACK DBGnEXEC DBGINSTRVALID DBGRNG[*] DBGCOMMTX DBGCOMMRX
}]
set_output_delay -clock CLK -max 5.000 [get_ports {
    MEM_VALID MEM_ADDR[*] MEM_WRITE MEM_WDATA[*] MEM_BYTE_ENABLE[*]
    MEM_CODE MEM_PRIVILEGED MEM_LOCK MEM_SEQUENTIAL MEM_MORE
    CPnMREQ CPSEQ CPnTRANS CPnOPC CPTBIT CPnI
    DBG_STEP_READY DBG_STEP_RSP_VALID DBG_STEP_TDO DBG_STEP_TDO_OE
    DBGACK DBGnEXEC DBGINSTRVALID DBGRNG[*] DBGCOMMTX DBGCOMMRX
}]
